[package]
name = "rewrite-protocol-vless"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
rewrite-io = { path = "../io" }
rewrite-model = { path = "../model" }
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
