[package]
name = "rewrite-config"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fancy-regex.workspace = true
ipnet.workspace = true
md-5.workspace = true
network-interface.workspace = true
prost.workspace = true
regex.workspace = true
rewrite-model = { path = "../model" }
rewrite-rules = { path = "../rules" }
rewrite-ruleset = { path = "../ruleset" }
serde.workspace = true
serde_yaml_ng.workspace = true
thiserror.workspace = true
url.workspace = true

[lints]
workspace = true
