[package]
name = "rewrite-outbound"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
bytes.workspace = true
fast-socks5.workspace = true
futures-util.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
rewrite-config = { path = "../config" }
rewrite-model = { path = "../model" }
rewrite-platform = { path = "../platform" }
rewrite-protocol-shadowsocks = { path = "../protocol-shadowsocks" }
rewrite-protocol-trojan = { path = "../protocol-trojan" }
rewrite-protocol-vless = { path = "../protocol-vless" }
rewrite-protocol-vmess = { path = "../protocol-vmess" }
rewrite-services = { path = "../services" }
rewrite-transport = { path = "../transport" }
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true

[lints]
workspace = true
