[package]
name = "rewrite-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
futures-util.workspace = true
notify.workspace = true
rewrite-config = { path = "../config" }
rewrite-controller = { path = "../controller" }
rewrite-dns = { path = "../dns" }
rewrite-inbound = { path = "../inbound" }
rewrite-model = { path = "../model" }
rewrite-net = { path = "../net" }
rewrite-outbound = { path = "../outbound" }
rewrite-platform = { path = "../platform" }
rewrite-rules = { path = "../rules" }
rewrite-services = { path = "../services" }
rewrite-state = { path = "../state" }
rand.workspace = true
reqwest.workspace = true
psl.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
url.workspace = true

[lints]
workspace = true
