[package]
name = "rewrite-controller"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axum.workspace = true
base64.workspace = true
futures-util.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
rustls-pemfile.workspace = true
rewrite-config = { path = "../config" }
rewrite-dns = { path = "../dns" }
rewrite-model = { path = "../model" }
rewrite-outbound = { path = "../outbound" }
rewrite-state = { path = "../state" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
tower.workspace = true
tower-http.workspace = true
time.workspace = true
url.workspace = true

[lints]
workspace = true
